# Generated by Django 4.1.1 on 2022-09-11 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_scheduler_added_date_remove_scheduler_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the person's name", max_length=30)),
                ('surname', models.CharField(help_text="Enter the person's family name", max_length=50)),
                ('job_title', models.CharField(help_text="Enter the person's job", max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='date_to_execute',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
